In [1]:
import numpy as np

In [2]:
simple_list=[1,2,3]

In [4]:
np.array(simple_list)

array([1, 2, 3])

In [5]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]

In [36]:
np.array(list_of_lists).argmin()

0

In [9]:
list_of_lists[1]

[4, 5, 6]

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,21,5)

array([ 0,  5, 10, 15, 20])

In [15]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [16]:
np.linspace(0,10,11)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [17]:
np.eye(4,4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [24]:
np.random.rand(1,3)

array([[ 0.56030081,  0.50569784,  0.64002859]])

In [31]:
np.random.randint(4,6,2)

array([4, 5])

In [27]:
np.arange(2)

array([0, 1])

In [28]:
sample_array=np.arange(30)

In [29]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [32]:
x=np.eye(4,4)

In [33]:
x.argmin()

1

In [37]:
sample_array.shape

(30,)

In [38]:
x=10;y="vikram"

In [48]:
z=np.array((x,x))

In [49]:
z.dtype

dtype('int32')

In [50]:
sample_array=np.arange(10,21)

In [51]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [52]:
samp=sample_array[0:4]

In [53]:
samp

array([10, 11, 12, 13])

In [54]:
samp[:]=67

In [55]:
sample_array

array([67, 67, 67, 67, 14, 15, 16, 17, 18, 19, 20])

In [56]:
sample_matrix = np.array( ( [1,2,3],[5,6,7] ) )

In [58]:
sample_matrix[0,:]

array([1, 2, 3])

In [59]:
sample_matrix

array([[1, 2, 3],
       [5, 6, 7]])

In [60]:
samp

array([67, 67, 67, 67])

In [61]:
np.savez("Both",first=samp,second=sample_matrix)

In [64]:
x=np.load("Both.npz")

In [65]:
x

In [66]:
x.keys()

['first', 'second']

In [67]:
x['first']

array([67, 67, 67, 67])

In [68]:
x

In [69]:
samp

array([67, 67, 67, 67])

In [70]:
samp.std()

0.0

In [71]:
import pandas as pd

In [72]:
labels=["x","y","w","z"]

In [73]:
list= range(10,40,4)

In [74]:
list

range(10, 40, 4)

In [75]:
range(10,40)

range(10, 40)

In [77]:
print(list)


range(10, 40, 4)


In [78]:
type(list)

range

In [79]:
list=[10,20,30,40]

In [80]:
array=np.array([10,20,30,40])

In [81]:
list;array

array([10, 20, 30, 40])

In [82]:
array

array([10, 20, 30, 40])

In [84]:
diction={'w':10,'x':20,"y":30,"z":40}

In [88]:
pd.Series(data=array,index=labels)

x    10
y    20
w    30
z    40
dtype: int32

In [87]:
labels

['x', 'y', 'w', 'z']

In [90]:
np.random.randn(5,3)

array([[ 1.36470021,  0.47483934,  0.67753852],
       [ 0.01510978,  0.59677593, -1.04648063],
       [-1.05987351,  0.38441895, -0.12669119],
       [ 0.15731977,  0.21011635, -1.78338186],
       [-0.08577261, -0.45234956, -1.71905793]])

In [91]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'], 
                    'B': ['B0', 'B1', 'B2', 'B3'], 
                    'C': ['C0', 'C1', 'C2', 'C3'], 
                    'D': ['D0', 'D1', 'D2', 'D3']}, 
                    index = [0, 1, 2, 3]) 

In [92]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [93]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'], 
                    'B': ['B4', 'B5', 'B6', 'B7'], 
                    'C': ['C4', 'C5', 'C6', 'C7'], 
                    'D': ['D4', 'D5', 'D6', 'D7']}, 
                    index = [4, 5, 6, 7]) 

In [94]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'], 
                    'B': ['B8', 'B9', 'B10', 'B11'], 
                    'C': ['C8', 'C9', 'C10', 'C11'], 
                    'D': ['D8', 'D9', 'D10', 'D11']}, 
                    index = [8, 9, 10, 11])

In [95]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [101]:
left = pd.DataFrame({'key': ['foo', 'bar'], 'val': [1, 2]}).set_index('key')
right = pd.DataFrame({'key': ['foo', 'bar'], 'val': [4, 5]}).set_index('key')

In [102]:
left


val
key     
foo    1
bar    2

In [103]:
newcolumn = 'A B'.split()
left['Alphabet']= newcolumn

In [104]:
left

val Alphabet
key              
foo    1        A
bar    2        B

In [105]:
data = {'prodID': ['101', '102', '103', '104', '104'],

                    'prodname': ['X', 'Y', 'Z', 'X', 'W'],

                     'profit': ['2738', '2727', '3497', '7347', '3743']}

In [107]:
dataframe = pd.DataFrame(data)

dataframe

grouped_data = dataframe.groupby('prodID')

grouped_data.max()


prodname profit
prodID                
101           X   2738
102           Y   2727
103           Z   3497
104           X   7347

In [108]:
grouped_data

In [109]:
grouped_data.dtypes

prodname  profit
prodID                 
101      object  object
102      object  object
103      object  object
104      object  object