In [275]:
import numpy as np   
import pandas as pd
import os

import seaborn as sns
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt   
import matplotlib.style
plt.style.use('classic')

import warnings
warnings.filterwarnings("ignore")

In [276]:
df=pd.read_csv("Computers.csv")

In [277]:
df.head(5)

Unnamed: 0  price  speed   hd  ram  screen  cd multi premium  ads
0           1   1499     25   80    4      14  no    no     yes   94
1           2   1795     33   85    2      14  no    no     yes   94
2           3   1595     25  170    4      15  no    no     yes   94
3           4   1849     25  170    8      14  no    no      no   94
4           5   3295     33  340   16      14  no    no     yes   94

In [278]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6259 entries, 0 to 6258
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  6259 non-null   int64 
 1   price       6259 non-null   int64 
 2   speed       6259 non-null   int64 
 3   hd          6259 non-null   int64 
 4   ram         6259 non-null   int64 
 5   screen      6259 non-null   int64 
 6   cd          6259 non-null   object
 7   multi       6259 non-null   object
 8   premium     6259 non-null   object
 9   ads         6259 non-null   int64 
dtypes: int64(7), object(3)
memory usage: 489.1+ KB


In [279]:
df.drop("Unnamed: 0",inplace=True,axis=1)

In [280]:
df.head(3)

price  speed   hd  ram  screen  cd multi premium  ads
0   1499     25   80    4      14  no    no     yes   94
1   1795     33   85    2      14  no    no     yes   94
2   1595     25  170    4      15  no    no     yes   94

In [281]:
dups = df.duplicated()
print('Number of duplicate rows = %d' % (dups.sum()))

df[dups]

Number of duplicate rows = 111


price  speed    hd  ram  screen   cd multi premium  ads
135    2195     25   245    8      14   no    no     yes   95
186    1695     33   170    4      14   no    no     yes   95
251    1499     25   170    4      14   no    no     yes  100
352    2595     50   250    8      15   no    no     yes  108
701    2099     33   120    4      14   no    no      no  176
...     ...    ...   ...  ...     ...  ...   ...     ...  ...
6254   1690    100   528    8      15   no    no     yes   39
6255   2223     66   850   16      15  yes   yes     yes   39
6256   2654    100  1200   24      15  yes    no     yes   39
6257   2195    100   850   16      15  yes    no     yes   39
6258   2490    100   850   16      17  yes    no     yes   39

[111 rows x 9 columns]

In [282]:
df.ads.value_counts()

339    339
307    307
298    298
292    292
283    283
275    275
273    273
267    267
259    259
249    249
248    248
246    246
225    225
216    216
205    205
191    191
182    182
176    176
163    163
162    162
158    158
152    152
139    139
132    132
129    129
108    108
100    100
95      95
94      94
39      78
75      75
52      52
51      51
40      40
Name: ads, dtype: int64

In [283]:
#cat=["speed","hd","ram","screen","cd","multi","premium","ads"]
cat=["cd","multi","premium"]

In [284]:
#df =pd.get_dummies(df, columns=cat,drop_first=True)

In [285]:
for feature in cat: 
    #if df[feature].dtype == 'object': 
        print('\n')
        print('feature:',feature)
        print(pd.Categorical(df[feature].unique()))
        print(pd.Categorical(df[feature].unique()).codes)
        df[feature] = pd.Categorical(df[feature]).codes



feature: cd
[no, yes]
Categories (2, object): [no, yes]
[0 1]


feature: multi
[no, yes]
Categories (2, object): [no, yes]
[0 1]


feature: premium
[yes, no]
Categories (2, object): [no, yes]
[1 0]


In [286]:
df

price  speed    hd  ram  screen  cd  multi  premium  ads
0      1499     25    80    4      14   0      0        1   94
1      1795     33    85    2      14   0      0        1   94
2      1595     25   170    4      15   0      0        1   94
3      1849     25   170    8      14   0      0        0   94
4      3295     33   340   16      14   0      0        1   94
...     ...    ...   ...  ...     ...  ..    ...      ...  ...
6254   1690    100   528    8      15   0      0        1   39
6255   2223     66   850   16      15   1      1        1   39
6256   2654    100  1200   24      15   1      0        1   39
6257   2195    100   850   16      15   1      0        1   39
6258   2490    100   850   16      17   1      0        1   39

[6259 rows x 9 columns]

In [287]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6259 entries, 0 to 6258
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   price    6259 non-null   int64
 1   speed    6259 non-null   int64
 2   hd       6259 non-null   int64
 3   ram      6259 non-null   int64
 4   screen   6259 non-null   int64
 5   cd       6259 non-null   int8 
 6   multi    6259 non-null   int8 
 7   premium  6259 non-null   int8 
 8   ads      6259 non-null   int64
dtypes: int64(6), int8(3)
memory usage: 311.9 KB


In [288]:
#sns.pairplot(df)

In [289]:
# Copy all the predictor variables into X dataframe
X = df.drop('price', axis=1)

y = df[['price']]

In [290]:
# Split X and y into training and test set in 75:25 ratio
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3 , random_state=1)

In [291]:
regression_model = LinearRegression()
regression_model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [292]:
# Let us explore the coefficients for each of the independent attributes

for idx, col_name in enumerate(X_train.columns):
    print("The coefficient for {} is {}".format(col_name, regression_model.coef_[0][idx]))

The coefficient for speed is 6.090389155457377
The coefficient for hd is -0.3282201590677298
The coefficient for ram is 78.20965090947976
The coefficient for screen is 99.7714769064026
The coefficient for cd is -106.05616760612635
The coefficient for multi is 13.96492053974317
The coefficient for premium is -372.4079256725116
The coefficient for ads is 1.275535751059145


In [293]:

intercept = regression_model.intercept_[0]

print("The intercept for our model is {}".format(intercept))

The intercept for our model is 33.11179667921624


In [294]:
regression_model.coef_

array([[ 6.09038916e+00, -3.28220159e-01,  7.82096509e+01,
         9.97714769e+01, -1.06056168e+02,  1.39649205e+01,
        -3.72407926e+02,  1.27553575e+00]])

In [295]:
# R square on training data
regression_model.score(X_train, y_train)

0.5297002608207861

In [296]:
# R square on testing data
regression_model.score(X_test, y_test)

0.533364479673687

In [297]:
# Train MSE
from sklearn.metrics import mean_squared_error
predictedPrice = regression_model.predict(X_train)
print(mean_squared_error(predictedPrice, y_train))

156457.92662269337


In [298]:
# Test MSE
from sklearn.metrics import mean_squared_error
predictedPrice = regression_model.predict(X_test)
print(mean_squared_error(predictedPrice, y_test))

162198.9165295923


In [326]:
np.sqrt(162198.9165295923) # Root MSE

402.73926618792996

In [313]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

In [314]:
ridge_model = Ridge(alpha=100)
ridge_model.fit(X_train, y_train)

Ridge(alpha=100, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [315]:
# Let us explore the coefficients for each of the independent attributes

for idx, col_name in enumerate(X_train.columns):
    print("The coefficient for {} is {}".format(col_name, regression_model.coef_[0][idx]))
    print("The coefficient for {} is {}".format(col_name, ridge_model.coef_[0][idx]))

The coefficient for speed is 6.090389155457377
The coefficient for speed is 6.025672039433667
The coefficient for hd is -0.3282201590677298
The coefficient for hd is -0.3336706219099728
The coefficient for ram is 78.20965090947976
The coefficient for ram is 77.33290719522202
The coefficient for screen is 99.7714769064026
The coefficient for screen is 98.21372074036994
The coefficient for cd is -106.05616760612635
The coefficient for cd is -96.02351502252526
The coefficient for multi is 13.96492053974317
The coefficient for multi is 0.36703088146085033
The coefficient for premium is -372.4079256725116
The coefficient for premium is -288.73928017155805
The coefficient for ads is 1.275535751059145
The coefficient for ads is 1.3066472909264122


In [318]:

for idx, col_name in enumerate(X_train.columns):
    print("The coefficient for {} is {}".format(col_name,(regression_model.coef_[0][idx]- ridge_model.coef_[0][idx]).round(1)))

The coefficient for speed is 0.1
The coefficient for hd is 0.0
The coefficient for ram is 0.9
The coefficient for screen is 1.6
The coefficient for cd is -10.0
The coefficient for multi is 13.6
The coefficient for premium is -83.7
The coefficient for ads is -0.0


In [319]:

lasso_model = Lasso(alpha=50)
lasso_model.fit(X_train, y_train)


Lasso(alpha=50, copy_X=True, fit_intercept=True, max_iter=1000, normalize=False,
      positive=False, precompute=False, random_state=None, selection='cyclic',
      tol=0.0001, warm_start=False)

In [320]:
lasso_model.coef_

array([ 5.64274234, -0.31984203, 71.04456999, 42.75477791, -0.        ,
       -0.        , -0.        ,  1.36624781])

In [321]:
ridge_model.coef_

array([[   6.02567204,   -0.33367062,   77.3329072 ,   98.21372074,
         -96.02351502,    0.36703088, -288.73928017,    1.30664729]])

In [322]:
ridge_model.score(X_test, y_test)

0.532320670217254

In [323]:
lasso_model.score(X_test, y_test)

0.48003505430396803

In [324]:
lin = regression_model.intercept_[0]
las = lasso_model.intercept_[0]
rid = ridge_model.intercept_[0]

In [325]:
print("linear :",lin," Ridge : ", rid," Lasso : ",las)

linear : 33.11179667921624  Ridge :  -16.936639699377793  Lasso :  539.5817144507153
