In [1]:
#########################################################################
##BASE Level Model for Machine Learning with imputing and Normalization
#########################################################################

In [2]:
import numpy as np
import pandas as pd  
import matplotlib.pyplot as plt   
import seaborn as sns
%matplotlib inline 

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
base = pd.read_csv("BaseExample-1.csv") 

In [5]:
baseClass=base.dropna(subset=['smoke'])

In [6]:
baseClass.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1997 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   sex       1997 non-null   object 
 1   age       1997 non-null   int64  
 2   edu       1997 non-null   object 
 3   unempdur  1380 non-null   float64
 4   income    1492 non-null   float64
 5   marital   1995 non-null   object 
 6   sport     1981 non-null   object 
 7   smoke     1997 non-null   object 
 8   alcabuse  1995 non-null   object 
 9   workab    1818 non-null   object 
 10  englang   1993 non-null   object 
 11  bmi       1968 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 202.8+ KB


In [7]:
baseClass['marital'].fillna(baseClass['marital'].mode()[0], inplace=True)
baseClass['alcabuse'].fillna(baseClass['alcabuse'].mode()[0], inplace=True)
baseClass['workab'].fillna(baseClass['workab'].mode()[0], inplace=True)
baseClass['englang'].fillna(baseClass['englang'].mode()[0], inplace=True)
baseClass['sport'].fillna(baseClass['sport'].mode()[0], inplace=True)
baseClass['unempdur'].fillna(baseClass['unempdur'].mean(), inplace=True)
baseClass['bmi'].fillna(baseClass['bmi'].mean(), inplace=True)
baseClass['income'].fillna(baseClass['income'].mean(), inplace=True)

In [8]:
x = baseClass.drop(columns=['smoke'])
y = baseClass['smoke']

In [9]:
x = pd.get_dummies(x, prefix_sep='_', drop_first=True)

In [10]:
# Split X and y into training and test set in 70:30 ratio
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=1)

In [11]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [12]:
# Invoking the NB Gaussian function to create the model
# fitting the model in the training data set
model = GaussianNB()
model.fit(x_train, y_train)
y_predict = model.predict(x_test)
model_score = model.score(x_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_predict))

0.7016666666666667
[[393  39]
 [140  28]]


In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
model = LogisticRegression()
model.fit(x_train, y_train)
y_predict = model.predict(x_test)
model_score = model.score(x_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_predict))

0.7216666666666667
[[423   9]
 [158  10]]


In [15]:
from sklearn import tree


clf = tree.DecisionTreeClassifier()
clf = clf.fit(x_train, y_train)

In [16]:
y_predict = clf.predict(x_test)
model_score = clf.score(x_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_predict))

0.6983333333333334
[[344  88]
 [ 93  75]]


In [17]:
#Import Random Forest Model
from sklearn.ensemble import RandomForestClassifier

#Create a Gaussian Classifier
clfRF=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clfRF.fit(x_train,y_train)

y_pred=clfRF.predict(x_test)
model_scoreRF = clfRF.score(x_test, y_test)

In [18]:
print(model_scoreRF)
print(metrics.confusion_matrix(y_test, y_pred))

0.7483333333333333
[[401  31]
 [120  48]]


In [19]:
from sklearn import svm

clfSVM = svm.SVC()
clfSVM.fit(x_train, y_train)
y_pred=clfSVM.predict(x_test)
model_scoreSVM = clfSVM.score(x_test, y_test)
print(model_scoreSVM)
print(metrics.confusion_matrix(y_test, y_pred))


0.72
[[432   0]
 [168   0]]


In [20]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
clfLDA = LinearDiscriminantAnalysis()
clfLDA.fit(x_train, y_train)
y_pred=clfLDA.predict(x_test)
model_scoreLDA = clfLDA.score(x_test, y_test)
print(model_scoreLDA)
print(metrics.confusion_matrix(y_test, y_pred))

0.7183333333333334
[[415  17]
 [152  16]]


In [21]:
from sklearn.ensemble import AdaBoostClassifier


clfADB = AdaBoostClassifier(n_estimators=100)
clfADB.fit(x_train,y_train)
y_pred=clfADB.predict(x_test)
model_scoreADB = clfADB.score(x_test, y_test)
print(model_scoreADB)
print(metrics.confusion_matrix(y_test, y_pred))

0.75
[[405  27]
 [123  45]]


In [22]:
from sklearn.neighbors import KNeighborsClassifier

clfKNN=KNeighborsClassifier()
clfKNN.fit(x_train,y_train)
y_pred=clfKNN.predict(x_test)
model_scoreKNN = clfKNN.score(x_test, y_test)
print(model_scoreKNN)
print(metrics.confusion_matrix(y_test, y_pred))

0.71
[[387  45]
 [129  39]]


In [23]:
import xgboost as xgb
clfXGB=xgb.XGBClassifier(random_state=1,learning_rate=0.01)
clfXGB.fit(x_train, y_train)
y_pred=clfXGB.predict(x_test)
model_scoreXGB=clfXGB.score(x_test,y_test)
print(model_scoreXGB)
print(metrics.confusion_matrix(y_test,y_pred))

0.715
[[413  19]
 [152  16]]


In [24]:
from sklearn.model_selection import cross_val_score
clfCVRF = RandomForestClassifier(n_estimators=100)
scores = cross_val_score(clfCVRF, x_train, y_train, cv=10)
scores


array([0.77142857, 0.77142857, 0.76428571, 0.77857143, 0.75714286,
       0.77857143, 0.72857143, 0.72661871, 0.77697842, 0.72661871])