In [203]:
import numpy as np   
import pandas as pd
import os

import seaborn as sns
import matplotlib.pyplot as plt   
import matplotlib.style
plt.style.use('classic')

import warnings
warnings.filterwarnings("ignore")

In [204]:
df = pd.read_csv("default_2k.csv") 

In [205]:
df.head()

default student     balance        income
0      No      No  412.071615  48347.296982
1      No     Yes  579.721305  18555.752586
2      No      No  694.398583  36570.425441
3      No      No    0.000000  41933.095770
4      No     Yes  407.340440  25376.728632

In [206]:
(df[df['default']=='Yes'].count()[0])/1994


0.03159478435305918

In [207]:
df.shape

(1994, 4)

In [208]:
df.columns;
cat=df[['default','student']]


In [210]:
df=pd.get_dummies(df, columns=cat.columns,drop_first=True)

In [211]:
df

balance        income  default_Yes  student_Yes
0      412.071615  48347.296982            0            0
1      579.721305  18555.752586            0            1
2      694.398583  36570.425441            0            0
3        0.000000  41933.095770            0            0
4      407.340440  25376.728632            0            1
...           ...           ...          ...          ...
1989   529.072681  43914.671430            0            0
1990   288.807950  30470.707013            0            0
1991  1186.098705  50353.925430            0            0
1992   270.224333  49128.037144            0            0
1993   640.639543  29236.630192            0            1

[1994 rows x 4 columns]

In [212]:
x=df.drop('default_Yes', axis=1)
y=df['default_Yes']
# Split X and y into training and test set in 75:25 ratio
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3 , random_state=1)

In [213]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

In [214]:
model = GaussianNB()
print(model)
model.fit(x_train, y_train)
model_score = model.score(x_train, y_train)
y_predict = model.predict(x_test)

print(model_score.round(4))
print(metrics.confusion_matrix(y_test, y_predict))

GaussianNB()
0.9699
[[582   0]
 [ 15   2]]


In [215]:
model_scoret = model.score(x_train, y_train)

In [216]:
model_scoret

0.9698924731182795

In [244]:
from sklearn import tree


DT_model= tree.DecisionTreeClassifier()
DT_model.fit(x_train, y_train)

DecisionTreeClassifier()

In [245]:
y_train_predict = DT_model.predict(x_train)
model_score = DT_model.score(x_train, y_train)
print(model_score)
print(metrics.confusion_matrix(y_train, y_train_predict))
print(metrics.classification_report(y_train, y_train_predict))

1.0
[[1349    0]
 [   0   46]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1349
           1       1.00      1.00      1.00        46

    accuracy                           1.00      1395
   macro avg       1.00      1.00      1.00      1395
weighted avg       1.00      1.00      1.00      1395



In [246]:
y_test_predict = DT_model.predict(x_test)
model_score = DT_model.score(x_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_train, y_train_predict))
print(metrics.classification_report(y_train, y_train_predict.ravel()))

0.9599332220367279
[[1349    0]
 [   0   46]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1349
           1       1.00      1.00      1.00        46

    accuracy                           1.00      1395
   macro avg       1.00      1.00      1.00      1395
weighted avg       1.00      1.00      1.00      1395



In [247]:
model_score_test = DT_model.score(x_test, y_test)
print(model_score_test)

0.9599332220367279


In [253]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=1)
x_test_res, y_test_res = sm.fit_sample(x_test, y_test)

In [254]:
y_test_predict = DT_model.predict(x_test)
model_score = DT_model.score(x_test_res, y_test_res)
print(model_score)


0.756872852233677


In [238]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=1) 
model = GaussianNB()
model.fit(x_train, y_train)
y_predict = model.predict(x_test)
model_score = model.score(x_train, y_train)
print(model_score)

0.9698924731182795


In [239]:
clf = tree.DecisionTreeClassifier(random_state=1)
clf = clf.fit(x_train, y_train)
y_predict = clf.predict(x_test)
model_score = clf.score(x_test, y_test)
print(model_score) 

0.9599332220367279


In [248]:
from imblearn.over_sampling import SMOTE 
sm = SMOTE(random_state=1)
x_train_res, y_train_res = sm.fit_sample(x_train, y_train)
clf_res = tree.DecisionTreeClassifier()
clf_res = clf.fit(x_train_res, y_train_res) 
y_predict = clf_res.predict(x_test)
model_score = clf_res.score(x_test, y_test)
print(model_score)

0.9248747913188647
