# Problem Statement - Food Nutrition


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [9]:
os.chdir("E:\AIMLGLIM\week1_files")
os.getcwd()

'E:\\AIMLGLIM\\week1_files'

In [10]:
data_df=pd.read_excel("Food Nutrition.xlsx")

In [15]:
x=5

In [16]:
type(x)

int

In [18]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 20 columns):
NDB_No             600 non-null int64
Shrt_Desc          600 non-null object
Water_(g)          600 non-null float64
Energ_Kcal         600 non-null int64
Protein_(g)        600 non-null float64
Lipid_Tot_(g)      599 non-null float64
Ash_(g)            599 non-null float64
Carbohydrt_(g)     600 non-null float64
Fiber_TD_(g)       600 non-null float64
Sugar_Tot_(g)      600 non-null float64
Calcium_(mg)       600 non-null int64
Iron_(mg)          600 non-null float64
Magnesium_(mg)     600 non-null int64
Phosphorus_(mg)    600 non-null int64
Potassium_(mg)     600 non-null int64
Sodium_(mg)        600 non-null int64
Zinc_(mg)          600 non-null float64
Copper_mg)         600 non-null float64
Manganese_(mg)     600 non-null float64
Selenium_(µg)      600 non-null float64
dtypes: float64(12), int64(7), object(1)
memory usage: 93.8+ KB


In [19]:
data_df.dtypes


NDB_No               int64
Shrt_Desc           object
Water_(g)          float64
Energ_Kcal           int64
Protein_(g)        float64
Lipid_Tot_(g)      float64
Ash_(g)            float64
Carbohydrt_(g)     float64
Fiber_TD_(g)       float64
Sugar_Tot_(g)      float64
Calcium_(mg)         int64
Iron_(mg)          float64
Magnesium_(mg)       int64
Phosphorus_(mg)      int64
Potassium_(mg)       int64
Sodium_(mg)          int64
Zinc_(mg)          float64
Copper_mg)         float64
Manganese_(mg)     float64
Selenium_(µg)      float64
dtype: object

In [20]:
df1


NameError: name 'df1' is not defined

In [24]:
s1 = pd.Series(['a', 'b'])
s2 = pd.Series(['c', 'd'])
pd.concat([s1, s2],axis=1)

0  1
0  a  c
1  b  d

In [25]:
demo_array=np.arange(0,10) 

In [27]:
demo_array
demo_array <3
demo_array[demo_array <6]
np.max(demo_array)

9

In [28]:
demo_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
demo_array <3


array([ True,  True,  True, False, False, False, False, False, False, False], dtype=bool)

In [30]:
demo_array[demo_array <6]


array([0, 1, 2, 3, 4, 5])

In [31]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))



In [32]:
demo_matrix[:, (1,2)]



array([[35, 74],
       [37, 37],
       [39, 93]])

In [33]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))



In [34]:
demo_matrix[2,3]



39

In [35]:
demo_array = np.arange(10,21)



In [36]:
demo_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
subset_demo_array = demo_array[0:7]



In [38]:
subset_demo_array


array([10, 11, 12, 13, 14, 15, 16])

In [39]:
subset_demo_array[:]= 101



In [40]:
subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [41]:
test_array = [10, 11.5, 12, 13.5, 14,15]   



In [42]:
test_array[2:3]



[12]

In [43]:
np.arange(0,22,6)


array([ 0,  6, 12, 18])

In [44]:
[import numpy as np]

SyntaxError: invalid syntax (<ipython-input-44-8c15f72de201>, line 1)

In [45]:
list_l =[[12,34,55,],[66,45,77],[45,77,88]]



In [46]:
np.array(list_l)



array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

In [47]:
score = [10, 15, 20, 25]

In [48]:
pd.Series(data=score, index = ['a','b','c','d'])



a    10
b    15
c    20
d    25
dtype: int64

In [49]:
df1


NameError: name 'df1' is not defined

In [50]:
data_df

NDB_No                                          Shrt_Desc  Water_(g)  \
0      1001                                   BUTTER,WITH SALT      15.87   
1      1002                             BUTTER,WHIPPED,W/ SALT      16.72   
2      1003                               BUTTER OIL,ANHYDROUS       0.24   
3      1004                                        CHEESE,BLUE      42.41   
4      1005                                       CHEESE,BRICK      41.11   
5      1006                                        CHEESE,BRIE      48.42   
6      1007                                   CHEESE,CAMEMBERT      51.80   
7      1008                                     CHEESE,CARAWAY      39.28   
8      1009                                     CHEESE,CHEDDAR      37.02   
9      1010                                    CHEESE,CHESHIRE      37.65   
10     1011                                       CHEESE,COLBY      38.20   
11     1012                CHEESE,COTTAGE,CRMD,LRG OR SML CURD      79.79   
12     1013                        CHEESE,COTTAGE,CRMD,W/FRUIT      79.64   
13     1014   CHEESE,COTTAGE,NONFAT,UNCRMD,DRY,LRG OR SML CURD      81.01   
14     1015                   CHEESE,COTTAGE,LOWFAT,2% MILKFAT      81.24   
15     1016                   CHEESE,COTTAGE,LOWFAT,1% MILKFAT      82.48   
16     1017                                       CHEESE,CREAM      52.62   
17     1018                                        CHEESE,EDAM      41.56   
18     1019                                        CHEESE,FETA      55.22   
19     1020                                     CHEESE,FONTINA      37.92   
20     1021                                     CHEESE,GJETOST      13.44   
21     1022                                       CHEESE,GOUDA      41.46   
22     1023                                     CHEESE,GRUYERE      33.19   
23     1024                                   CHEESE,LIMBURGER      48.42   
24     1025                                    CHEESE,MONTEREY      41.01   
25     1026                         CHEESE,MOZZARELLA,WHL MILK      50.01   
26     1027                CHEESE,MOZZARELLA,WHL MILK,LO MOIST      48.38   
27     1028                   CHEESE,MOZZARELLA,PART SKIM MILK      53.78   
28     1029               CHEESE,MOZZARELLA,LO MOIST,PART-SKIM      47.07   
29     1030                                    CHEESE,MUENSTER      41.77   
..      ...                                                ...        ...   
570    3869  INF FORMULA,MEAD JOHNSON,ENFAMIL,LACTOFREE,W/ ...       2.20   
571    3870  CHI FORMU,ABBT NUTR,PEDIASU,RTF,W/ IRON & FIB ...      80.47   
572    3900  INF FORMULA,NESTLE,GOOD START 2 ESSENTIALS,W/ ...      86.60   
573    3901  INF FORMULA, NE,GOO STAR 2 ESSENT,W/ IRON,LIQ ...      74.20   
574    3913  INF FORMULA,NESTLE,GOOD START 2 ESSENTIALS,W/ ...       2.50   
575    3925  INF FORMULA,NESTLE,GOOD START ESSENTIALS SOY,W...      87.50   
576    3926  INF FORM,NEST,GOOD START ESSENT SOY,W/ IRON,LI...      75.40   
577    3928  INF FORMULA,NESTLE,GOOD START ESSENTIALS SOY,W...       2.50   
578    3929  INF FORMULA, MEAD JOHNSON,NEXT STEP PROSOBEE,P...       3.00   
579    3930  INF FORMULA,MEAD JOHNSON,NEXT STEP PROSOBEE,PR...      86.41   
580    3934                   BABYFOOD,CORN & SWT POTATOES,STR      82.62   
581    3935  INF FORM, ABBO NUTR, SIMIL, ALIMENT, ADVAN, RT...      87.32   
582    3936  INF FORMULA,PBM PRODUC,STO BRA,RTF (FORMERLY W...      88.10   
583    3937  INF FORM,PBM PROD,STORE BRAND,LC,NOT REC (FORM...      76.00   
584    3938           INF FORMULA,PBM PRODUCTS,STORE BRAND,PDR       2.00   
585    3939       INF FORMULA,PBM PRODUCTS,STORE BRAND,SOY,RTF      88.00   
586    3940  INF FORMU,PBM PRODU,STORE BR,SOY,LIQ CONC,NOT ...      76.00   
587    3941       INF FORMULA,PBM PRODUCTS,STORE BRAND,SOY,PDR       2.00   
588    3942  INF FORMULA, MEAD JOHNS, ENFAMI, AR LIPIL, RTF...      87.00   
589    3943  INF FORMULA, MEA JOHNSO, ENFAMI, AR LIPIL, PDR...       3.00   
5

In [51]:
data_df([1,2])

TypeError: 'DataFrame' object is not callable